# Generated by Django 2.0 on 2018-01-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karbar', '0005_auto_20180130_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madadkar',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.MyUser')),
                ('employment_date', models.DateField(blank=True, null=True)),
            ],
            bases=('karbar.myuser',),
        ),
    ]
