# Generated by Django 2.0 on 2018-01-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0011_auto_20180130_1624'),
        ('madadju', '0008_report'),
        ('madadkar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receive', models.DateField()),
                ('date_send', models.DateField()),
                ('content', models.CharField(max_length=500)),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamyar.Hamyar')),
                ('madadju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju')),
                ('madadkar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadkar.Madadkar')),
            ],
        ),
    ]
