# Generated by Django 2.0 on 2018-01-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0002_letter_message_need_report_urgentneed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='hamyar',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='madadju',
        ),
        migrations.RemoveField(
            model_name='message',
            name='madadju',
        ),
        migrations.RemoveField(
            model_name='need',
            name='madadju',
        ),
        migrations.RemoveField(
            model_name='report',
            name='madadju',
        ),
        migrations.RemoveField(
            model_name='urgentneed',
            name='madadju',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Need',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UrgentNeed',
        ),
    ]
