# Generated by Django 2.0 on 2018-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0003_auto_20180130_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar',
            name='report_method',
            field=models.IntegerField(choices=[(1, 'email'), (0, 'text')]),
        ),
    ]
