# Generated by Django 2.0 on 2018-01-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madadju', '0008_report'),
        ('hamyar', '0005_auto_20180130_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapt',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamyar.Hamyar')),
                ('madadju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('date', models.DateField()),
                ('payment_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.IntegerField(max_length=100)),
                ('madadju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadju.Madadju')),
            ],
        ),
    ]
