# Generated by Django 2.0 on 2018-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0006_adapt_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar',
            name='report_method',
            field=models.IntegerField(choices=[(1, 'email'), (0, 'text')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.IntegerField(),
        ),
    ]
