# Generated by Django 2.0 on 2018-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamyar', '0007_auto_20180130_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
