# Generated by Django 2.0 on 2018-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0002_auto_20180130_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'modir'), (2, 'hamyar'), (1, 'madadkar'), (3, 'madadju')]),
        ),
    ]
