# Generated by Django 2.0 on 2018-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0006_auto_20180130_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
